// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// comparePairwise_C
List comparePairwise_C(NumericVector position_of_kegg_enzyme_A, NumericVector position_of_kegg_enzyme_B, NumericMatrix expressions, NumericMatrix ranks);
RcppExport SEXP ctr_comparePairwise_C(SEXP position_of_kegg_enzyme_ASEXP, SEXP position_of_kegg_enzyme_BSEXP, SEXP expressionsSEXP, SEXP ranksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type position_of_kegg_enzyme_A(position_of_kegg_enzyme_ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type position_of_kegg_enzyme_B(position_of_kegg_enzyme_BSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type expressions(expressionsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ranks(ranksSEXP);
    rcpp_result_gen = Rcpp::wrap(comparePairwise_C(position_of_kegg_enzyme_A, position_of_kegg_enzyme_B, expressions, ranks));
    return rcpp_result_gen;
END_RCPP
}
// Cor_Matrix_C
List Cor_Matrix_C(NumericVector v1, NumericVector v2, NumericMatrix expression, NumericMatrix ranks);
RcppExport SEXP ctr_Cor_Matrix_C(SEXP v1SEXP, SEXP v2SEXP, SEXP expressionSEXP, SEXP ranksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v1(v1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type v2(v2SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type expression(expressionSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ranks(ranksSEXP);
    rcpp_result_gen = Rcpp::wrap(Cor_Matrix_C(v1, v2, expression, ranks));
    return rcpp_result_gen;
END_RCPP
}
// which_rows_with_no_sd_cpp
NumericVector which_rows_with_no_sd_cpp(NumericMatrix x);
RcppExport SEXP ctr_which_rows_with_no_sd_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(which_rows_with_no_sd_cpp(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"ctr_comparePairwise_C", (DL_FUNC) &ctr_comparePairwise_C, 4},
    {"ctr_Cor_Matrix_C", (DL_FUNC) &ctr_Cor_Matrix_C, 4},
    {"ctr_which_rows_with_no_sd_cpp", (DL_FUNC) &ctr_which_rows_with_no_sd_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ctr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
