# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Individual_KO_background
#' @export
Individual_KO_background <- function(RNAseqExpressionCounts, RNAseqExpressionRanks, KOTerms, allBins, HighQBins, N) {
    .Call('ctr_Individual_KO_background', PACKAGE = 'ctr', RNAseqExpressionCounts, RNAseqExpressionRanks, KOTerms, allBins, HighQBins, N)
}

which_rows_with_no_sd_cpp <- function(x) {
    .Call('ctr_which_rows_with_no_sd_cpp', PACKAGE = 'ctr', x)
}

