# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@export
comparePairwise_C <- function(position_of_kegg_enzyme_A, position_of_kegg_enzyme_B, expressions, ranks) {
    .Call('ctr_comparePairwise_C', PACKAGE = 'ctr', position_of_kegg_enzyme_A, position_of_kegg_enzyme_B, expressions, ranks)
}

#'@export
Cor_Matrix_C <- function(v1, v2, expression, ranks) {
    .Call('ctr_Cor_Matrix_C', PACKAGE = 'ctr', v1, v2, expression, ranks)
}

#'@export
which_rows_with_no_sd_cpp <- function(x) {
    .Call('ctr_which_rows_with_no_sd_cpp', PACKAGE = 'ctr', x)
}

